my_string=str("emobilis")
my_int=int(6)
my_float=float(34.8)
my_complex_number=1j
my_bool1=bool(True)
my_bool2=bool(False)
my_list=(["sally", "katty", "kevin"])
my_tuple=(("banana","mangoes","appples","melonnie"))
my_set=set({"toyota","lexus","nissan","mercedes"})
my_dictionary=dict({"name":"saline","salary": 3839443})

print(type(my_dictionary))
print(type(my_set))
print(43<55)
print(6>4)
